'use client';

import { useMemo } from 'react';
import { motion } from 'framer-motion';
import { 
  DollarSign, Download, CheckCircle2, TrendingDown, ArrowRight, ExternalLink, Sparkles
} from 'lucide-react';
import {
  Bar, BarChart, ResponsiveContainer, XAxis, YAxis, Tooltip, Legend, Cell
} from 'recharts';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { ChartContainer, ChartTooltip, ChartTooltipContent } from '@/components/ui/chart';
import type { PricingAnalysis, PricingItem } from '@/types';

const chartConfig = {
  current: { label: 'Current Cost', color: '#ef4444' },
  recommended: { label: 'Recommended', color: '#22c55e' },
};

function generateExcel(pricing: PricingAnalysis, projectName: string) {
  // Build CSV content (universally openable as Excel)
  const headers = ['Service', 'Type', 'Status', 'Current Cost ($/mo)', 'Alternative', 'Alternative Cost ($/mo)', 'Billing Cycle', 'Source URL'];
  const rows = pricing.items.map(item => [
    item.name,
    item.type,
    item.is_paid ? 'PAID' : 'FREE',
    item.current_cost.toFixed(2),
    item.alternative_name || '-',
    (item.alternative_cost ?? 0).toFixed(2),
    item.billing_cycle || 'monthly',
    item.alternative_url || '',
  ]);

  // Summary rows
  rows.push([]);
  rows.push(['SUMMARY', '', '', '', '', '', '', '']);
  rows.push(['Total Current Monthly Cost', '', '', pricing.total_current.toFixed(2), '', '', '', '']);
  rows.push(['Total Recommended Monthly Cost', '', '', '', '', pricing.total_recommended.toFixed(2), '', '']);
  rows.push(['Potential Monthly Savings', '', '', (pricing.total_current - pricing.total_recommended).toFixed(2), '', '', '', '']);
  rows.push([]);
  rows.push([`Generated by StackShadow - ${new Date().toLocaleDateString()}`, '', '', '', '', '', '', '']);

  const csvContent = [headers, ...rows]
    .map(row => row.map(cell => `"${String(cell).replace(/"/g, '""')}"`).join(','))
    .join('\n');

  const blob = new Blob(['\uFEFF' + csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${projectName.replace(/[^a-zA-Z0-9]/g, '_')}_cost_analysis.csv`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

interface PricingBlockProps {
  pricing: PricingAnalysis | null;
  projectName: string;
}

export function PricingBlock({ pricing, projectName }: PricingBlockProps) {
  if (!pricing) return null;

  const paidItems = useMemo(() => pricing.items.filter(i => i.is_paid), [pricing.items]);
  const freeItems = useMemo(() => pricing.items.filter(i => !i.is_paid), [pricing.items]);
  const savings = pricing.total_current - pricing.total_recommended;
  const savingsPct = pricing.total_current > 0 ? Math.round((savings / pricing.total_current) * 100) : 0;

  // All free stack
  if (paidItems.length === 0) {
    return (
      <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}>
        <Card className="border-green-500/20 bg-green-500/5 backdrop-blur-md overflow-hidden relative">
          <div className="absolute top-0 right-0 p-6 opacity-10"><CheckCircle2 className="w-24 h-24 text-green-500" /></div>
          <CardHeader>
            <div className="flex items-center gap-3">
              <div className="p-2 bg-green-500/20 rounded-xl"><Sparkles className="w-5 h-5 text-green-400" /></div>
              <div>
                <CardTitle className="font-sans text-xl font-medium">All Free Stack</CardTitle>
                <CardDescription className="font-mono text-xs uppercase tracking-widest text-green-400/80 mt-1">
                  No paid APIs or services detected - {freeItems.length} tools, $0/mo
                </CardDescription>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <div className="flex flex-wrap gap-2">
              {freeItems.slice(0, 12).map(item => (
                <Badge key={item.name} variant="outline" className="border-green-500/20 text-green-400 font-mono text-xs">
                  <CheckCircle2 className="w-3 h-3 mr-1" /> {item.name}
                </Badge>
              ))}
            </div>
          </CardContent>
        </Card>
      </motion.div>
    );
  }

  // Chart data for paid items
  const chartData = paidItems.map(item => ({
    name: item.name.length > 15 ? item.name.slice(0, 14) + '…' : item.name,
    fullName: item.name,
    current: item.current_cost,
    recommended: item.alternative_cost ?? item.current_cost,
    alternativeName: item.alternative_name || 'Same',
    alternativeUrl: item.alternative_url || '',
  }));

  return (
    <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-6">
      {/* Summary Card */}
      <Card className="border-border/50 bg-card/50 backdrop-blur-md overflow-hidden relative">
        <div className="absolute top-0 right-0 p-6 opacity-5"><DollarSign className="w-24 h-24" /></div>
        <CardHeader>
          <div className="flex items-center justify-between flex-wrap gap-4">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-accent/20 rounded-xl"><DollarSign className="w-5 h-5 text-accent" /></div>
              <div>
                <CardTitle className="font-sans text-xl font-medium">Cost Analysis</CardTitle>
                <CardDescription className="font-mono text-xs uppercase tracking-widest mt-1">
                  {paidItems.length} paid service{paidItems.length !== 1 ? 's' : ''} • {freeItems.length} free
                </CardDescription>
              </div>
            </div>
            <Button
              variant="outline"
              size="sm"
              className="rounded-full border-border/50 hover:bg-muted font-mono text-xs tracking-widest uppercase"
              onClick={() => generateExcel(pricing, projectName)}
            >
              <Download className="w-3 h-3 mr-2" />
              Export Spreadsheet
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          {/* Cost Summary Boxes */}
          <div className="grid grid-cols-3 gap-4 mb-8">
            <div className="p-4 rounded-xl bg-red-500/5 border border-red-500/10">
              <p className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">Current Monthly</p>
              <p className="text-2xl font-sans font-medium text-red-400 mt-1">${pricing.total_current.toFixed(0)}</p>
              <p className="font-mono text-[10px] text-muted-foreground/60 mt-1">per month</p>
            </div>
            <div className="p-4 rounded-xl bg-green-500/5 border border-green-500/10">
              <p className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">Recommended</p>
              <p className="text-2xl font-sans font-medium text-green-400 mt-1">${pricing.total_recommended.toFixed(0)}</p>
              <p className="font-mono text-[10px] text-muted-foreground/60 mt-1">per month</p>
            </div>
            <div className="p-4 rounded-xl bg-accent/5 border border-accent/10">
              <p className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">Savings</p>
              <div className="flex items-baseline gap-2 mt-1">
                <p className="text-2xl font-sans font-medium text-accent">${savings.toFixed(0)}</p>
                {savingsPct > 0 && (
                  <Badge className="bg-accent/20 text-accent border-accent/20 text-[10px]">
                    <TrendingDown className="w-3 h-3 mr-1" />{savingsPct}%
                  </Badge>
                )}
              </div>
              <p className="font-mono text-[10px] text-muted-foreground/60 mt-1">per month</p>
            </div>
          </div>

          {/* Grouped Bar Chart */}
          <div className="h-[280px]">
            <ChartContainer config={chartConfig} className="h-full w-full">
              <BarChart data={chartData} barGap={4} barCategoryGap="20%">
                <XAxis
                  dataKey="name"
                  axisLine={false}
                  tickLine={false}
                  tick={{ fontSize: 9, fill: 'rgba(128,128,128,0.7)', fontFamily: 'monospace' }}
                  interval={0}
                  angle={-20}
                  textAnchor="end"
                  height={50}
                />
                <YAxis
                  axisLine={false}
                  tickLine={false}
                  tick={{ fontSize: 9, fill: 'rgba(128,128,128,0.5)', fontFamily: 'monospace' }}
                  tickFormatter={(v: number) => `$${v}`}
                  width={50}
                />
                <Tooltip
                  content={({ active, payload }) => {
                    if (!active || !payload?.length) return null;
                    const d = payload[0]?.payload;
                    return (
                      <div className="bg-card border border-border rounded-xl p-3 shadow-xl text-xs font-mono">
                        <p className="font-sans font-medium text-sm mb-2">{d?.fullName}</p>
                        <p className="text-red-400">Current: ${d?.current}/mo</p>
                        <p className="text-green-400">Alternative: ${d?.recommended}/mo ({d?.alternativeName})</p>
                      </div>
                    );
                  }}
                />
                <Bar dataKey="current" fill="#ef4444" radius={[4, 4, 0, 0]} name="Current Cost" />
                <Bar dataKey="recommended" fill="#22c55e" radius={[4, 4, 0, 0]} name="Recommended" />
              </BarChart>
            </ChartContainer>
          </div>

          {/* Legend */}
          <div className="flex items-center justify-center gap-8 mt-4">
            <div className="flex items-center gap-2">
              <div className="w-3 h-3 rounded-sm bg-red-500" />
              <span className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">Current Cost</span>
            </div>
            <div className="flex items-center gap-2">
              <div className="w-3 h-3 rounded-sm bg-green-500" />
              <span className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">Recommended Alternative</span>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Detailed Breakdown */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {paidItems.map((item, i) => (
          <Card key={i} className="border-border/50 bg-card/50 backdrop-blur-md">
            <CardContent className="p-5">
              <div className="flex items-start justify-between mb-3">
                <div>
                  <p className="font-sans text-sm font-medium">{item.name}</p>
                  <Badge variant="outline" className="font-mono text-[8px] border-border/50 mt-1">{item.type}</Badge>
                </div>
                <div className="text-right">
                  <p className="font-mono text-lg text-red-400">${item.current_cost}<span className="text-[10px] text-muted-foreground">/mo</span></p>
                </div>
              </div>
              {item.alternative_name && (
                <div className="mt-3 p-3 rounded-lg bg-green-500/5 border border-green-500/10">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <ArrowRight className="w-3 h-3 text-green-400" />
                      <span className="font-mono text-xs text-green-400">{item.alternative_name}</span>
                    </div>
                    <span className="font-mono text-sm text-green-400">${item.alternative_cost ?? 0}/mo</span>
                  </div>
                  {item.alternative_url && (
                    <a href={item.alternative_url} target="_blank" rel="noreferrer" className="flex items-center gap-1 mt-2 text-[10px] font-mono text-muted-foreground hover:text-accent transition-colors">
                      <ExternalLink className="w-3 h-3" /> Learn more
                    </a>
                  )}
                </div>
              )}
              {item.billing_cycle && (
                <p className="font-mono text-[10px] text-muted-foreground/50 mt-2">Billing: {item.billing_cycle}</p>
              )}
            </CardContent>
          </Card>
        ))}
      </div>
    </motion.div>
  );
}
